#=============================================================================
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    automatic_update = false  # `:SPUpdate SpaceVim` for manual update
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = false

    default_indent = 4
    expand_tab = true

    filemanager = "nerdtree"

    # statusline:nerd fonts required
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    statusline_left_sections = [
        'winnr',
        'filename',
        'version control info'
    ]
    statusline_right_sections = [
        'major mode',
        'minor mode lighters'
        'fileformat',
        'cursorpos',
        'percentage'
    ]
    enable_statusline_display_mode = false
    enable_statusline_mode = false

    snippet_engine = 'ultisnips'

    # Buffer
    buffer_index_type = 1
    enable_os_fileformat_icon = 1
    enable_tabline_filetype_icon = true

    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"

    autocomplete_method = "coc"  # Enable COC as the auto-completion engine
    # autocomplete_method = "deoplete"

    # File manager
    filetree_direction = "right"

    # NOTE: the value should be a list, and each item is the name of the plugin.
    #disabled_plugins = ["vim-python-pep8-indent"]

    # Snippet

    # Misc
    vim_help_language = "cn"

[[layers]]
    name = "checkers"
    # Linter
    enable_neomake = true
    enable_ale = false
    lint_on_the_fly = true

[[layers]]
  name = "autocomplete"
  auto_completion_return_key_behavior = "smart"
  auto_completion_tab_key_behavior = "smart"
  auto_completion_delay = 100
  auto_completion_complete_with_key_sequence = "fd"
  auto_completion_complete_with_key_sequence_delay = 0.1

[[layers]]
  name = "format"
  enable = true

[[layers]]
  name = "lang#python"
  python_file_head = [
      '#!/usr/bin/env python',
      '# -*- coding: utf-8 -*-',
      '',
      ''
  ]
  python_interpreter = '/opt/conda/bin/python'
  format_on_save = true
  enable_typeinfo = true
  enabled_linters = ['python', 'pylint']

[[layers]]
  name = "lang#csharp"
  highlight_types = 0

# [[layers]]
#   name = "lang#html"

# [[layers]]
#   name = "lang#ipynb"

[[layers]]
  name = "lang#markdown"

[[layers]]
  name = "lang#sh"

[[layers]]
  name = "test"

[[layers]]
  name = "tmux"
  tmux_navigator_modifier = "alt"

[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30

[[layers]]
  name = 'github'

[[layers]]
  name = 'git'

#[[layers]]
#  name = "lsp"
#  filetypes = [
#    "python",
#]

#[[layers]]
#  name = "chinese"

[[layers]]
  name = "debug"

[[layers]]
  name = "ui"
  enable_sidebar = true

# [[layers]]
#   name = "colorscheme"
#   random_theme = true
#   frequency = "1h"

# [[layers]]
#   name = "VersionControl"

[[layers]]
  name = "denite"

[[layers]]
  # Enable bookmarks
  name = "tools"

# fzf can be installed using: conda install -c conda-forge fzf
[[layers]]
  name = "fzf"

# [[layers]]
#   # Linters
#   name = "checkers"

[[custom_plugins]]
  name = "christoomey/vim-tmux-navigator"
  merged = false

[[custom_plugins]]
  name = "fisadev/vim-isort"
  merged = false

[[custom_plugins]]
  name = "tmux-plugins/vim-tmux-focus-events"
  merged = false

[[custom_plugins]]
  name = "ntpeters/vim-better-whitespace"
  merged = false

[[custom_plugins]]
    name = "editorconfig/editorconfig-vim"
    merged = false

[[custom_plugins]]
  name = "rkitover/vimpager"
  merged = false

[[custom_plugins]]
  name = "wincent/ferret"
  merged = false

[[custom_plugins]]
  name = "nelstrom/vim-visual-star-search"
  merged = false

[[custom_plugins]]
  name = "neomake/neomake"
  merged = false

[[custom_plugins]]
  name = "tomlion/vim-solidity"
  merged = false

[[custom_plugins]]
  # This allows jumping to test files
  # Check out: https://www.dev-log.me/Jump_between_test_files_and_implementation_in_Vim/
  name = 'tpope/vim-projectionist'
  merged = false

# [[custom_plugins]]
#   # required for fzf as it changes working directory to project root
#   name = "airblade/vim-rooter"
#   merged = false


# [[custom_plugins]]
#   name = 'Shougo/vimfiler.vim'
#   merged = false

# [[custom_plugins]]
#   name = "vim-airline/vim-airline"
#   merged = false
# 
# [[custom_plugins]]
#   name = "vim-airline/vim-airline-themes"
#   merged = false

# [[custom_plugins]]
#     name = "tmhedberg/SimpylFold"
#     merged = 0
